// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.DAL.Data;

namespace SmartHome.DAL.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SmartHome.BLL.Entities.Enums.TemperatureVariant", b =>
                {
                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("integer")
                        .HasColumnName("temperature_unit");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("TemperatureUnit")
                        .HasName("pk_temperature_variant");

                    b.ToTable("temperature_variant");

                    b.HasData(
                        new
                        {
                            TemperatureUnit = 1,
                            Name = "Celsius"
                        },
                        new
                        {
                            TemperatureUnit = 2,
                            Name = "Fahrenheit"
                        },
                        new
                        {
                            TemperatureUnit = 3,
                            Name = "Kelvin"
                        });
                });

            modelBuilder.Entity("SmartHome.BLL.Entities.Temperature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("SensorName")
                        .HasColumnType("text")
                        .HasColumnName("sensor_name");

                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("integer")
                        .HasColumnName("temperature_unit");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_temperatures");

                    b.ToTable("temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
